extends: airbnb
env:
  browser: true
  node: true
  es6: true
parser: babel-eslint
plugins: [react]
rules:
  array-callback-return: 0
  camelcase: 0
  class-methods-use-this: 0
  comma-dangle: [1, never]
  func-names: 0
  generator-star-spacing: [0, {before: true, after: false}]
  guard-for-in: 0
  linebreak-style: [2, unix]
  no-console: off
  no-param-reassign: [1, { props: true, ignorePropertyModificationsFor: [errors, columnObject] }]
  no-unused-vars: [1, { args: none }]
  semi: 0
  react/no-array-index-key: 0
  react/require-default-props: 0 # to be removed
  react/prop-types: 0 # to be removed
  react/forbid-prop-types: 0
  react/no-children-prop: 0
  react/jsx-no-bind: 0
  react/jsx-filename-extension: 0
  react/no-unescaped-entities: 0
